// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: learner.proto

package learner

import (
	model "github.com/jt05610/petri/v1/testModel"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Learning *model.Result `protobuf:"bytes,1,opt,name=learning,proto3,oneof" json:"learning,omitempty"`
}

func (x *CompleteRequest) Reset() {
	*x = CompleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_learner_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteRequest) ProtoMessage() {}

func (x *CompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_learner_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteRequest.ProtoReflect.Descriptor instead.
func (*CompleteRequest) Descriptor() ([]byte, []int) {
	return file_learner_proto_rawDescGZIP(), []int{0}
}

func (x *CompleteRequest) GetLearning() *model.Result {
	if x != nil {
		return x.Learning
	}
	return nil
}

type CompleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Learned *model.Store `protobuf:"bytes,1,opt,name=learned,proto3,oneof" json:"learned,omitempty"`
	Updated *model.Store `protobuf:"bytes,2,opt,name=updated,proto3,oneof" json:"updated,omitempty"`
}

func (x *CompleteResponse) Reset() {
	*x = CompleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_learner_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteResponse) ProtoMessage() {}

func (x *CompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_learner_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteResponse.ProtoReflect.Descriptor instead.
func (*CompleteResponse) Descriptor() ([]byte, []int) {
	return file_learner_proto_rawDescGZIP(), []int{1}
}

func (x *CompleteResponse) GetLearned() *model.Store {
	if x != nil {
		return x.Learned
	}
	return nil
}

func (x *CompleteResponse) GetUpdated() *model.Store {
	if x != nil {
		return x.Updated
	}
	return nil
}

type LearnRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result  *model.Result `protobuf:"bytes,1,opt,name=result,proto3,oneof" json:"result,omitempty"`
	Learned *model.Store  `protobuf:"bytes,2,opt,name=learned,proto3,oneof" json:"learned,omitempty"`
}

func (x *LearnRequest) Reset() {
	*x = LearnRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_learner_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LearnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LearnRequest) ProtoMessage() {}

func (x *LearnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_learner_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LearnRequest.ProtoReflect.Descriptor instead.
func (*LearnRequest) Descriptor() ([]byte, []int) {
	return file_learner_proto_rawDescGZIP(), []int{2}
}

func (x *LearnRequest) GetResult() *model.Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *LearnRequest) GetLearned() *model.Store {
	if x != nil {
		return x.Learned
	}
	return nil
}

type LearnResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Learning *model.Result `protobuf:"bytes,1,opt,name=learning,proto3,oneof" json:"learning,omitempty"`
}

func (x *LearnResponse) Reset() {
	*x = LearnResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_learner_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LearnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LearnResponse) ProtoMessage() {}

func (x *LearnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_learner_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LearnResponse.ProtoReflect.Descriptor instead.
func (*LearnResponse) Descriptor() ([]byte, []int) {
	return file_learner_proto_rawDescGZIP(), []int{3}
}

func (x *LearnResponse) GetLearning() *model.Result {
	if x != nil {
		return x.Learning
	}
	return nil
}

var File_learner_proto protoreflect.FileDescriptor

var file_learner_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x65, 0x72, 0x1a, 0x1a, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4e, 0x0a, 0x0f, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x08, 0x6c, 0x65, 0x61, 0x72, 0x6e,
	0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x08, 0x6c, 0x65, 0x61, 0x72,
	0x6e, 0x69, 0x6e, 0x67, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x6c, 0x65, 0x61, 0x72,
	0x6e, 0x69, 0x6e, 0x67, 0x22, 0x84, 0x01, 0x0a, 0x10, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x07, 0x6c, 0x65, 0x61,
	0x72, 0x6e, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x48, 0x00, 0x52, 0x07, 0x6c, 0x65, 0x61, 0x72,
	0x6e, 0x65, 0x64, 0x88, 0x01, 0x01, 0x12, 0x2b, 0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x48, 0x01, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x65, 0x64, 0x42,
	0x0a, 0x0a, 0x08, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x22, 0x7e, 0x0a, 0x0c, 0x4c,
	0x65, 0x61, 0x72, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x88, 0x01, 0x01, 0x12, 0x2b, 0x0a, 0x07, 0x6c, 0x65, 0x61, 0x72, 0x6e,
	0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x48, 0x01, 0x52, 0x07, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x65,
	0x64, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42,
	0x0a, 0x0a, 0x08, 0x5f, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x65, 0x64, 0x22, 0x4c, 0x0a, 0x0d, 0x4c,
	0x65, 0x61, 0x72, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x08,
	0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52,
	0x08, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09,
	0x5f, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x32, 0x89, 0x01, 0x0a, 0x0e, 0x4c, 0x65,
	0x61, 0x72, 0x6e, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3f, 0x0a, 0x08,
	0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x18, 0x2e, 0x6c, 0x65, 0x61, 0x72, 0x6e,
	0x65, 0x72, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x6d,
	0x70, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a,
	0x05, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x12, 0x15, 0x2e, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x65, 0x72,
	0x2e, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x6c, 0x65, 0x61, 0x72, 0x6e, 0x65, 0x72, 0x2e, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x21, 0x5a, 0x1f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f,
	0x6c, 0x65, 0x61, 0x72, 0x6e, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31,
	0x2f, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_learner_proto_rawDescOnce sync.Once
	file_learner_proto_rawDescData = file_learner_proto_rawDesc
)

func file_learner_proto_rawDescGZIP() []byte {
	file_learner_proto_rawDescOnce.Do(func() {
		file_learner_proto_rawDescData = protoimpl.X.CompressGZIP(file_learner_proto_rawDescData)
	})
	return file_learner_proto_rawDescData
}

var file_learner_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_learner_proto_goTypes = []interface{}{
	(*CompleteRequest)(nil),  // 0: learner.CompleteRequest
	(*CompleteResponse)(nil), // 1: learner.CompleteResponse
	(*LearnRequest)(nil),     // 2: learner.LearnRequest
	(*LearnResponse)(nil),    // 3: learner.LearnResponse
	(*model.Result)(nil),     // 4: model.Result
	(*model.Store)(nil),      // 5: model.Store
}
var file_learner_proto_depIdxs = []int32{
	4, // 0: learner.CompleteRequest.learning:type_name -> model.Result
	5, // 1: learner.CompleteResponse.learned:type_name -> model.Store
	5, // 2: learner.CompleteResponse.updated:type_name -> model.Store
	4, // 3: learner.LearnRequest.result:type_name -> model.Result
	5, // 4: learner.LearnRequest.learned:type_name -> model.Store
	4, // 5: learner.LearnResponse.learning:type_name -> model.Result
	0, // 6: learner.LearnerService.Complete:input_type -> learner.CompleteRequest
	2, // 7: learner.LearnerService.Learn:input_type -> learner.LearnRequest
	1, // 8: learner.LearnerService.Complete:output_type -> learner.CompleteResponse
	3, // 9: learner.LearnerService.Learn:output_type -> learner.LearnResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_learner_proto_init() }
func file_learner_proto_init() {
	if File_learner_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_learner_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_learner_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_learner_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LearnRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_learner_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LearnResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_learner_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_learner_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_learner_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_learner_proto_msgTypes[3].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_learner_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_learner_proto_goTypes,
		DependencyIndexes: file_learner_proto_depIdxs,
		MessageInfos:      file_learner_proto_msgTypes,
	}.Build()
	File_learner_proto = out.File
	file_learner_proto_rawDesc = nil
	file_learner_proto_goTypes = nil
	file_learner_proto_depIdxs = nil
}
