# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import autosampler_pb2 as autosampler__pb2


class AutosamplerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Inject = channel.unary_stream(
                '/autosampler.Autosampler/Inject',
                request_serializer=autosampler__pb2.InjectRequest.SerializeToString,
                response_deserializer=autosampler__pb2.InjectResponse.FromString,
                )


class AutosamplerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Inject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AutosamplerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Inject': grpc.unary_stream_rpc_method_handler(
                    servicer.Inject,
                    request_deserializer=autosampler__pb2.InjectRequest.FromString,
                    response_serializer=autosampler__pb2.InjectResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'autosampler.Autosampler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Autosampler(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Inject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/autosampler.Autosampler/Inject',
            autosampler__pb2.InjectRequest.SerializeToString,
            autosampler__pb2.InjectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
