# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: autosampler.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61utosampler.proto\x12\x0b\x61utosampler\"\x8f\x01\n\rInjectRequest\x12\x0c\n\x04vial\x18\x01 \x01(\x05\x12\x13\n\x0b\x61ir_cushion\x18\x02 \x01(\x05\x12\x15\n\rexcess_volume\x18\x03 \x01(\x05\x12\x14\n\x0c\x66lush_volume\x18\x04 \x01(\x05\x12\x18\n\x10injection_volume\x18\x05 \x01(\x05\x12\x14\n\x0cneedle_depth\x18\x06 \x01(\x05\"9\n\x0eInjectResponse\x12\'\n\x05state\x18\x01 \x01(\x0e\x32\x18.autosampler.InjectState*4\n\x0bInjectState\x12\x08\n\x04Idle\x10\x00\x12\r\n\tInjecting\x10\x01\x12\x0c\n\x08Injected\x10\x02\x32R\n\x0b\x41utosampler\x12\x43\n\x06Inject\x12\x1a.autosampler.InjectRequest\x1a\x1b.autosampler.InjectResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autosampler_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INJECTSTATE']._serialized_start=239
  _globals['_INJECTSTATE']._serialized_end=291
  _globals['_INJECTREQUEST']._serialized_start=35
  _globals['_INJECTREQUEST']._serialized_end=178
  _globals['_INJECTRESPONSE']._serialized_start=180
  _globals['_INJECTRESPONSE']._serialized_end=237
  _globals['_AUTOSAMPLER']._serialized_start=293
  _globals['_AUTOSAMPLER']._serialized_end=375
# @@protoc_insertion_point(module_scope)
