// messages we need to send

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.4
// source: v1/marlin.proto

package marlin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Position struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// xyz position in mm
	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	// xyz position in mm
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	// xyz position in mm
	Z float32 `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	// xyz position in mm
	E float32 `protobuf:"fixed32,4,opt,name=e,proto3" json:"e,omitempty"`
}

func (x *Position) Reset() {
	*x = Position{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_marlin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_v1_marlin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_v1_marlin_proto_rawDescGZIP(), []int{0}
}

func (x *Position) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Position) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *Position) GetE() float32 {
	if x != nil {
		return x.E
	}
	return 0
}

type State struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position *Position `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Speed    float32   `protobuf:"fixed32,2,opt,name=speed,proto3" json:"speed,omitempty"`
}

func (x *State) Reset() {
	*x = State{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_marlin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_v1_marlin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_v1_marlin_proto_rawDescGZIP(), []int{1}
}

func (x *State) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *State) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

type StateStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StateStreamRequest) Reset() {
	*x = StateStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_marlin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateStreamRequest) ProtoMessage() {}

func (x *StateStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_marlin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateStreamRequest.ProtoReflect.Descriptor instead.
func (*StateStreamRequest) Descriptor() ([]byte, []int) {
	return file_v1_marlin_proto_rawDescGZIP(), []int{2}
}

type StateStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State     *State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Timestamp string `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *StateStreamResponse) Reset() {
	*x = StateStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_marlin_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateStreamResponse) ProtoMessage() {}

func (x *StateStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_marlin_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateStreamResponse.ProtoReflect.Descriptor instead.
func (*StateStreamResponse) Descriptor() ([]byte, []int) {
	return file_v1_marlin_proto_rawDescGZIP(), []int{3}
}

func (x *StateStreamResponse) GetState() *State {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *StateStreamResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type HomeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Axis:
	//
	//	*HomeRequest_All
	//	*HomeRequest_X
	//	*HomeRequest_Y
	//	*HomeRequest_Z
	Axis isHomeRequest_Axis `protobuf_oneof:"axis"`
}

func (x *HomeRequest) Reset() {
	*x = HomeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_marlin_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HomeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeRequest) ProtoMessage() {}

func (x *HomeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_marlin_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeRequest.ProtoReflect.Descriptor instead.
func (*HomeRequest) Descriptor() ([]byte, []int) {
	return file_v1_marlin_proto_rawDescGZIP(), []int{4}
}

func (m *HomeRequest) GetAxis() isHomeRequest_Axis {
	if m != nil {
		return m.Axis
	}
	return nil
}

func (x *HomeRequest) GetAll() bool {
	if x, ok := x.GetAxis().(*HomeRequest_All); ok {
		return x.All
	}
	return false
}

func (x *HomeRequest) GetX() bool {
	if x, ok := x.GetAxis().(*HomeRequest_X); ok {
		return x.X
	}
	return false
}

func (x *HomeRequest) GetY() bool {
	if x, ok := x.GetAxis().(*HomeRequest_Y); ok {
		return x.Y
	}
	return false
}

func (x *HomeRequest) GetZ() bool {
	if x, ok := x.GetAxis().(*HomeRequest_Z); ok {
		return x.Z
	}
	return false
}

type isHomeRequest_Axis interface {
	isHomeRequest_Axis()
}

type HomeRequest_All struct {
	All bool `protobuf:"varint,1,opt,name=all,proto3,oneof"`
}

type HomeRequest_X struct {
	X bool `protobuf:"varint,2,opt,name=X,proto3,oneof"`
}

type HomeRequest_Y struct {
	Y bool `protobuf:"varint,3,opt,name=Y,proto3,oneof"`
}

type HomeRequest_Z struct {
	Z bool `protobuf:"varint,4,opt,name=Z,proto3,oneof"`
}

func (*HomeRequest_All) isHomeRequest_Axis() {}

func (*HomeRequest_X) isHomeRequest_Axis() {}

func (*HomeRequest_Y) isHomeRequest_Axis() {}

func (*HomeRequest_Z) isHomeRequest_Axis() {}

type MoveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// xyz position in mm
	X *float32 `protobuf:"fixed32,1,opt,name=x,proto3,oneof" json:"x,omitempty"`
	// xyz position in mm
	Y *float32 `protobuf:"fixed32,2,opt,name=y,proto3,oneof" json:"y,omitempty"`
	// xyz position in mm
	Z *float32 `protobuf:"fixed32,3,opt,name=z,proto3,oneof" json:"z,omitempty"`
	// xyz position in mm
	E *float32 `protobuf:"fixed32,4,opt,name=e,proto3,oneof" json:"e,omitempty"`
	// speed in mm/min
	Speed *float32 `protobuf:"fixed32,5,opt,name=speed,proto3,oneof" json:"speed,omitempty"`
}

func (x *MoveRequest) Reset() {
	*x = MoveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_marlin_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveRequest) ProtoMessage() {}

func (x *MoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_marlin_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveRequest.ProtoReflect.Descriptor instead.
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return file_v1_marlin_proto_rawDescGZIP(), []int{5}
}

func (x *MoveRequest) GetX() float32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *MoveRequest) GetY() float32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

func (x *MoveRequest) GetZ() float32 {
	if x != nil && x.Z != nil {
		return *x.Z
	}
	return 0
}

func (x *MoveRequest) GetE() float32 {
	if x != nil && x.E != nil {
		return *x.E
	}
	return 0
}

func (x *MoveRequest) GetSpeed() float32 {
	if x != nil && x.Speed != nil {
		return *x.Speed
	}
	return 0
}

type MoveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *MoveResponse) Reset() {
	*x = MoveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_marlin_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveResponse) ProtoMessage() {}

func (x *MoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_marlin_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveResponse.ProtoReflect.Descriptor instead.
func (*MoveResponse) Descriptor() ([]byte, []int) {
	return file_v1_marlin_proto_rawDescGZIP(), []int{6}
}

func (x *MoveResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FanOnRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FanOnRequest) Reset() {
	*x = FanOnRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_marlin_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FanOnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FanOnRequest) ProtoMessage() {}

func (x *FanOnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_marlin_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FanOnRequest.ProtoReflect.Descriptor instead.
func (*FanOnRequest) Descriptor() ([]byte, []int) {
	return file_v1_marlin_proto_rawDescGZIP(), []int{7}
}

type FanOnResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *FanOnResponse) Reset() {
	*x = FanOnResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_marlin_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FanOnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FanOnResponse) ProtoMessage() {}

func (x *FanOnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_marlin_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FanOnResponse.ProtoReflect.Descriptor instead.
func (*FanOnResponse) Descriptor() ([]byte, []int) {
	return file_v1_marlin_proto_rawDescGZIP(), []int{8}
}

func (x *FanOnResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FanOffRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FanOffRequest) Reset() {
	*x = FanOffRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_marlin_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FanOffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FanOffRequest) ProtoMessage() {}

func (x *FanOffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_marlin_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FanOffRequest.ProtoReflect.Descriptor instead.
func (*FanOffRequest) Descriptor() ([]byte, []int) {
	return file_v1_marlin_proto_rawDescGZIP(), []int{9}
}

type FanOffResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *FanOffResponse) Reset() {
	*x = FanOffResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_marlin_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FanOffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FanOffResponse) ProtoMessage() {}

func (x *FanOffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_marlin_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FanOffResponse.ProtoReflect.Descriptor instead.
func (*FanOffResponse) Descriptor() ([]byte, []int) {
	return file_v1_marlin_proto_rawDescGZIP(), []int{10}
}

func (x *FanOffResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are assignable to Response:
	//
	//	*Response_State
	//	*Response_Move
	Response isResponse_Response `protobuf_oneof:"response"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_marlin_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_v1_marlin_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_v1_marlin_proto_rawDescGZIP(), []int{11}
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (m *Response) GetResponse() isResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *Response) GetState() *State {
	if x, ok := x.GetResponse().(*Response_State); ok {
		return x.State
	}
	return nil
}

func (x *Response) GetMove() *MoveResponse {
	if x, ok := x.GetResponse().(*Response_Move); ok {
		return x.Move
	}
	return nil
}

type isResponse_Response interface {
	isResponse_Response()
}

type Response_State struct {
	State *State `protobuf:"bytes,2,opt,name=state,proto3,oneof"`
}

type Response_Move struct {
	Move *MoveResponse `protobuf:"bytes,3,opt,name=move,proto3,oneof"`
}

func (*Response_State) isResponse_Response() {}

func (*Response_Move) isResponse_Response() {}

var File_v1_marlin_proto protoreflect.FileDescriptor

var file_v1_marlin_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x76, 0x31, 0x2f, 0x6d, 0x61, 0x72, 0x6c, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x42, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0c, 0x0a,
	0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x7a, 0x12, 0x0c, 0x0a, 0x01, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x01, 0x65, 0x22, 0x44, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x25,
	0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x09, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x22, 0x14, 0x0a, 0x12, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x51, 0x0a, 0x13, 0x53, 0x74, 0x61, 0x74, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x22, 0x59, 0x0a, 0x0b, 0x48, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x03, 0x61, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x48, 0x00, 0x52, 0x03, 0x61, 0x6c, 0x6c, 0x12, 0x0e, 0x0a, 0x01, 0x58, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x48, 0x00, 0x52, 0x01, 0x58, 0x12, 0x0e, 0x0a, 0x01, 0x59, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x48, 0x00, 0x52, 0x01, 0x59, 0x12, 0x0e, 0x0a, 0x01, 0x5a, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x08, 0x48, 0x00, 0x52, 0x01, 0x5a, 0x42, 0x06, 0x0a, 0x04, 0x61, 0x78, 0x69, 0x73, 0x22,
	0x96, 0x01, 0x0a, 0x0b, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x11, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x48, 0x00, 0x52, 0x01, 0x78, 0x88,
	0x01, 0x01, 0x12, 0x11, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x48, 0x01, 0x52,
	0x01, 0x79, 0x88, 0x01, 0x01, 0x12, 0x11, 0x0a, 0x01, 0x7a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02,
	0x48, 0x02, 0x52, 0x01, 0x7a, 0x88, 0x01, 0x01, 0x12, 0x11, 0x0a, 0x01, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x02, 0x48, 0x03, 0x52, 0x01, 0x65, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x73,
	0x70, 0x65, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x48, 0x04, 0x52, 0x05, 0x73, 0x70,
	0x65, 0x65, 0x64, 0x88, 0x01, 0x01, 0x42, 0x04, 0x0a, 0x02, 0x5f, 0x78, 0x42, 0x04, 0x0a, 0x02,
	0x5f, 0x79, 0x42, 0x04, 0x0a, 0x02, 0x5f, 0x7a, 0x42, 0x04, 0x0a, 0x02, 0x5f, 0x65, 0x42, 0x08,
	0x0a, 0x06, 0x5f, 0x73, 0x70, 0x65, 0x65, 0x64, 0x22, 0x28, 0x0a, 0x0c, 0x4d, 0x6f, 0x76, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x0e, 0x0a, 0x0c, 0x46, 0x61, 0x6e, 0x4f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x29, 0x0a, 0x0d, 0x46, 0x61, 0x6e, 0x4f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x0f, 0x0a,
	0x0d, 0x46, 0x61, 0x6e, 0x4f, 0x66, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2a,
	0x0a, 0x0e, 0x46, 0x61, 0x6e, 0x4f, 0x66, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x75, 0x0a, 0x08, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x1e, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x06, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x23, 0x0a, 0x04, 0x6d, 0x6f, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52,
	0x04, 0x6d, 0x6f, 0x76, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x32, 0xd8, 0x01, 0x0a, 0x06, 0x4d, 0x61, 0x72, 0x6c, 0x69, 0x6e, 0x12, 0x21, 0x0a, 0x04,
	0x48, 0x6f, 0x6d, 0x65, 0x12, 0x0c, 0x2e, 0x48, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x09, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x3c, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x13,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x21, 0x0a,
	0x04, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x0c, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x23, 0x0a, 0x05, 0x46, 0x61, 0x6e, 0x4f, 0x6e, 0x12, 0x0d, 0x2e, 0x46, 0x61, 0x6e, 0x4f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x25, 0x0a, 0x06, 0x46, 0x61, 0x6e, 0x4f, 0x66, 0x66, 0x12,
	0x0e, 0x2e, 0x46, 0x61, 0x6e, 0x4f, 0x66, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x09, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09,
	0x76, 0x31, 0x2f, 0x6d, 0x61, 0x72, 0x6c, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_v1_marlin_proto_rawDescOnce sync.Once
	file_v1_marlin_proto_rawDescData = file_v1_marlin_proto_rawDesc
)

func file_v1_marlin_proto_rawDescGZIP() []byte {
	file_v1_marlin_proto_rawDescOnce.Do(func() {
		file_v1_marlin_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_marlin_proto_rawDescData)
	})
	return file_v1_marlin_proto_rawDescData
}

var file_v1_marlin_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_v1_marlin_proto_goTypes = []interface{}{
	(*Position)(nil),            // 0: Position
	(*State)(nil),               // 1: State
	(*StateStreamRequest)(nil),  // 2: StateStreamRequest
	(*StateStreamResponse)(nil), // 3: StateStreamResponse
	(*HomeRequest)(nil),         // 4: HomeRequest
	(*MoveRequest)(nil),         // 5: MoveRequest
	(*MoveResponse)(nil),        // 6: MoveResponse
	(*FanOnRequest)(nil),        // 7: FanOnRequest
	(*FanOnResponse)(nil),       // 8: FanOnResponse
	(*FanOffRequest)(nil),       // 9: FanOffRequest
	(*FanOffResponse)(nil),      // 10: FanOffResponse
	(*Response)(nil),            // 11: Response
}
var file_v1_marlin_proto_depIdxs = []int32{
	0,  // 0: State.position:type_name -> Position
	1,  // 1: StateStreamResponse.state:type_name -> State
	1,  // 2: Response.state:type_name -> State
	6,  // 3: Response.move:type_name -> MoveResponse
	4,  // 4: Marlin.Home:input_type -> HomeRequest
	2,  // 5: Marlin.StateStream:input_type -> StateStreamRequest
	5,  // 6: Marlin.Move:input_type -> MoveRequest
	7,  // 7: Marlin.FanOn:input_type -> FanOnRequest
	9,  // 8: Marlin.FanOff:input_type -> FanOffRequest
	11, // 9: Marlin.Home:output_type -> Response
	3,  // 10: Marlin.StateStream:output_type -> StateStreamResponse
	11, // 11: Marlin.Move:output_type -> Response
	11, // 12: Marlin.FanOn:output_type -> Response
	11, // 13: Marlin.FanOff:output_type -> Response
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_v1_marlin_proto_init() }
func file_v1_marlin_proto_init() {
	if File_v1_marlin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_marlin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Position); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_marlin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*State); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_marlin_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_marlin_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_marlin_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HomeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_marlin_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_marlin_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_marlin_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FanOnRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_marlin_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FanOnResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_marlin_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FanOffRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_marlin_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FanOffResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_marlin_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_v1_marlin_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*HomeRequest_All)(nil),
		(*HomeRequest_X)(nil),
		(*HomeRequest_Y)(nil),
		(*HomeRequest_Z)(nil),
	}
	file_v1_marlin_proto_msgTypes[5].OneofWrappers = []interface{}{}
	file_v1_marlin_proto_msgTypes[11].OneofWrappers = []interface{}{
		(*Response_State)(nil),
		(*Response_Move)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_marlin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_marlin_proto_goTypes,
		DependencyIndexes: file_v1_marlin_proto_depIdxs,
		MessageInfos:      file_v1_marlin_proto_msgTypes,
	}.Build()
	File_v1_marlin_proto = out.File
	file_v1_marlin_proto_rawDesc = nil
	file_v1_marlin_proto_goTypes = nil
	file_v1_marlin_proto_depIdxs = nil
}
