package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.42

import (
	"context"

	"github.com/jt05610/petri"
	"github.com/jt05610/petri/graph/generated"
)

// AcceptedTokens is the resolver for the acceptedTokens field.
func (r *placeInputResolver) AcceptedTokens(ctx context.Context, obj *petri.PlaceInput, data []string) error {
	tokens, err := r.tokenSchema.List(ctx, &petri.TokenFilter{
		ID: &petri.StringSelector{
			In: data,
		},
	})
	if err != nil {
		return err
	}
	obj.AcceptedTokens = tokens
	return nil
}

// PlaceInput returns generated.PlaceInputResolver implementation.
func (r *Resolver) PlaceInput() generated.PlaceInputResolver { return &placeInputResolver{r} }

type placeInputResolver struct{ *Resolver }
